### ISSUE TITLE
Blank Page after Deployment and configuration

### ISSUE THREAD

**Issue by blacktee** [Microsoft/Partner-Center-Storefront#11]
1. Try
Deployment via PartnerCenter under Partner Settings -> Storefrontt
-> Failed but resources where created, Result: Blank web page

2. Try
Downloaded Partner-Center-Storefront repository
Configured the existing parameters correctly
All assets and templates where deployed into blob storage
Both app registrations have required permissions
-> Deployment succeeded without error, Result: Blank web page

3. Try
Added _artifactsLocation, _artifactsLocationSasToken, StoreFrontPackageFolder, StoreFrontPackageFileName Parameters in website.json/website.parameters.json
Both app registrations have required permissions
-> Deployment suceeded without errors, Result: Blank web page

4. Try
Contacted Microsoft Support
Response:
The problem doesn't seem to be connected to the subdomain, unfortunately after several tests we have the same result in the test area. Unfortunately we don't have any technical support available on this section, as stated in the following document, point 6.

Could there be any issues with the Key Vault?
If i execute the Web Page locally it breaks with the error: No endpoint defined in global.asax.cs line 39, ApplicationDomain.BootstrapAsync()

Is there anything I'm doing wrong (+MS Support)?

Greetings and thanks for help

**Comment by blacktee** [comment]
![image](https://user-images.githubusercontent.com/4079928/50300760-b11add00-0485-11e9-9600-fd186a8c4625.png)

This is what my console says

**Comment by blacktee** [comment]
> Same mistake here:
> ![storefront](https://user-images.githubusercontent.com/7565973/50345590-e7149b80-052f-11e9-8357-5b17d2267957.PNG)

The first SyntaxError is because of the (in my case) German Resources.de.resx.
Under "Back <-> Zurück" you have to remove the line break.

**Comment by andreaslillich** [comment]
The first SyntaxError is because of the (in my case) German Resources.de.resx.
Under "Back <-> Zurück" you have to remove the line break.

Thanks, that was the first mistake.

There was an error in German Resources.de.resx.
Delete the quotes
Under "Undo <-> "Rückgängig"" 
Then I was able to configure the store.

**Comment by blacktee** [comment]
> The first SyntaxError is because of the (in my case) German Resources.de.resx.
> Under "Back <-> Zurück" you have to remove the line break.
> 
> Thanks, that was the first mistake.
> 
> There was an error in German Resources.de.resx.
> Delete the quotes
> Under "Undo <-> "Rückgängig""
> Then I was able to configure the store.

Did you changed anything else than the translation in the Resources.de.resx?

I still have the $WebPortal is not defined Error...
