### ISSUE TITLE
https://blogs.msdn.microsoft.com/iwilliams/2016/12/17/reseller-storefront/ not available

### ISSUE THREAD

**Issue by Agazoth** [microsoft/Partner-Center-Storefront#13]
The info page for the project is not available.

**Comment by blakejakopovic** [comment]
An archived snapshot is available at:
https://web.archive.org/web/20190108030926/https://blogs.msdn.microsoft.com/iwilliams/2016/12/17/reseller-storefront/

**Comment by isaiahwilliams** [comment]
Access to the blog has been restored. In the near feature I will be moving that post to a new platform to ensure that it will continue to be available as changes to our blog platform are made.
