### ISSUE TITLE
Cannot choose Country

### ISSUE THREAD

**Issue by CarlosOHmx** [microsoft/Partner-Center-Storefront#18]
Hi. 

We have set up our Storefront at https://office365mexico.azurewebsites.net/, but we are having some problems. Whenever a client wants to purchase an Office 365 subscription, they can't, because once in the shopping cart, they need to choose a country. The problem is that the dropdown list of countries is empty and one can't just type a country name.

Has anyone else had this problem? Any solutions?

Here is the image of the error:

[Webstorefront Error - 28 May 2019.docx](https://github.com/microsoft/Partner-Center-Storefront/files/3238132/Webstorefront.Error.-.28.May.2019.docx)

Thanks!

**Comment by isaiahwilliams** [comment]
There have been several enhancements made over the past couple of weeks. Can you update to the latest version and see if the issue still persist?

**Comment by isaiahwilliams** [comment]
Please let us know if you are still having an issue.
