### ISSUE TITLE
Deployment template validation failed: 'The template resource 'Microsoft.Web/sites/<webSiteName>' cannot reference itself. Please see https://aka.ms/arm-template-expressions/#reference for usage details.'

### ISSUE THREAD

**Issue by rebelanger** [microsoft/Partner-Center-Storefront#25]
# Steps to reproduce

> What steps can reproduce the defect?

- Click on the "Deploy to Azure" link in README.md file;
- Fill out the form with all appropriate values (e.g. web site name with max 15 characters);
- Click on "Next";
- Got the following error:

"Deployment template validation failed: 'The template resource 'Microsoft.Web/sites/<webSiteName>' cannot reference itself. Please see https://aka.ms/arm-template-expressions/#reference for usage details.'."

**Comment by isaiahwilliams** [comment]
This error can occur if you are using the same name for the host plan and website. Minor updates were just made to help prevent this error
